// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3btwsP9UyjhUGBiVzYzuMShBY5Hixvhg',
    appId: '1:268939449244:web:f508ce8acdbbd66e54ee59',
    messagingSenderId: '268939449244',
    projectId: 'pa-mobilekb-2',
    authDomain: 'pa-mobilekb-2.firebaseapp.com',
    storageBucket: 'pa-mobilekb-2.firebasestorage.app',
    measurementId: 'G-YKLVPSZMZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ4FtWKu9fPCvHcLxed2KgHRSHiLVi_jA',
    appId: '1:268939449244:android:38a01921d59116a654ee59',
    messagingSenderId: '268939449244',
    projectId: 'pa-mobilekb-2',
    storageBucket: 'pa-mobilekb-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCz1w-SY4ZyflB_GYWUjaioq-bsSJtwNM',
    appId: '1:268939449244:ios:15e4e422472a640f54ee59',
    messagingSenderId: '268939449244',
    projectId: 'pa-mobilekb-2',
    storageBucket: 'pa-mobilekb-2.firebasestorage.app',
    iosBundleId: 'com.example.klasifikasiFelidae',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCz1w-SY4ZyflB_GYWUjaioq-bsSJtwNM',
    appId: '1:268939449244:ios:15e4e422472a640f54ee59',
    messagingSenderId: '268939449244',
    projectId: 'pa-mobilekb-2',
    storageBucket: 'pa-mobilekb-2.firebasestorage.app',
    iosBundleId: 'com.example.klasifikasiFelidae',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3btwsP9UyjhUGBiVzYzuMShBY5Hixvhg',
    appId: '1:268939449244:web:ecbbe975301124f254ee59',
    messagingSenderId: '268939449244',
    projectId: 'pa-mobilekb-2',
    authDomain: 'pa-mobilekb-2.firebaseapp.com',
    storageBucket: 'pa-mobilekb-2.firebasestorage.app',
    measurementId: 'G-9HX7TQGMQ6',
  );
}
